mod_id=jumpdelayfix
mod_name=Jump Delay Fix
mod_group=com.kizio.jumpdelayfix
mod_author=kizio
mod_license=Apache-2.0
mod_description=Lightweight client-side mod for smoother, more responsive jumping with multiplayer-friendly behavior.
mod_version=1.3.0-SNAPSHOT
mod_icon=assets/jumpdelayfix/icon.png
mod_homepage=https://modrinth.com/mod/jump-delay-fix
mod_sources=https://github.com/kizio806/jump-delay-fix
mod_issues=https://github.com/kizio806/jump-delay-fix/issues

minecraft_version=26.2
fabric_minecraft_version_range=>=26.2 <26.3
fabric_game_versions=26.2
neoforge_game_versions=26.2
modrinth_game_versions=26.2
minecraft_version_range=[26.2,26.3)
resource_pack_format=34
data_pack_format=48
yarn_mappings=
loader_version=0.18.4
fabric_api_version=0.159.0+26.2
modmenu_version=20.0.1
neoforge_moddev_gradle_version=2.0.146
neoforge_version=26.2.0.79
neoforge_loader_range=[26,)
javafml_loader_range=[4,)

java_version=25
loom_version=1.15-SNAPSHOT

org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
